export const ADD_CHARACTER = 'ADD_CHARACTER'
export const DELETE_CHARACTER = 'DELETE_CHARACTER'

export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE'
export const ADD_FAVORITE = 'ADD_FAVORITE'
export const DELETE_FAVORITE = 'DELETE_FAVORITE'

export const FILTER_BY_GENRE = 'FILTER_BY_GENRE'
export const FILTER_BY_STATUS = 'FILTER_BY_STATUS'
export const FILTER_BY_SPECIE = 'FILTER_BY_SPECIE'
export const CLEANED_FILTER = 'CLEANED_FILTER'

export const IS_ACCESS_PERMITED = 'IS_ACCESS_PERMITED'
